namespace AnythingCanBeFarming.Data;

// USDA PLANTS data from the EOL Darwin Core Archive, staged exactly as the source states it.
// All strings are untrusted source text; never render them as HTML.
public sealed class UsdaTaxon
{
    public long Id { get; set; }
    public required string Symbol { get; set; }
    public required string ScientificName { get; set; }
    public string? CanonicalName { get; set; }
    // USDA's own (often older) family circumscription, e.g. Aceraceae. Never use it as the family.
    public string? FamilyUsda { get; set; }
    public string? TaxonRank { get; set; }
    public string? TaxonomicStatus { get; set; }
    public string? SourceUrl { get; set; }
    public bool IsCurrent { get; set; }
    public long ImportId { get; set; }
}

public sealed class UsdaFact
{
    public long Id { get; set; }
    public long UsdaTaxonId { get; set; }
    public required string Symbol { get; set; }
    public required string OccurrenceId { get; set; }
    public required string TypeUri { get; set; }
    public required string ValueRaw { get; set; }
    // Generated by PostgreSQL from ValueRaw (UsdaCode.FromValue); never written by the application.
    public string ValueCode { get; private set; } = "";
    public decimal? ValueNumeric { get; set; }
    public string? UnitUri { get; set; }
    public string? BodyPartUri { get; set; }
    public string? LifeStageUri { get; set; }
    public string? StatisticalMethod { get; set; }
    public string? SourceTerm { get; set; }
    public long? RemarkId { get; set; }
    // measurementMethod, deduplicated like remarks. It is what tells the two height facts apart.
    public long? MethodRemarkId { get; set; }
    public string? SourceUrl { get; set; }
    public long ImportId { get; set; }
}

public sealed class UsdaRemark
{
    public long Id { get; set; }
    public required string Sha256 { get; set; }
    public required string Text { get; set; }
}

public sealed class UsdaDistribution
{
    public long Id { get; set; }
    public long UsdaTaxonId { get; set; }
    public required string Symbol { get; set; }
    public required string Kind { get; set; }
    public required string PlaceRaw { get; set; }
    public required string PlaceScheme { get; set; }
    public string? PlaceId { get; set; }
    // measurementRemarks name the place as USDA states it, e.g. "Georgia" for GeoNames 614540 (the country's ID).
    public long? RemarkId { get; set; }
    public long ImportId { get; set; }
}

public sealed class UsdaWfoLink
{
    public long Id { get; set; }
    public long UsdaTaxonId { get; set; }
    public required string Symbol { get; set; }
    public long? WfoTaxonId { get; set; }
    public long? AcceptedWfoTaxonId { get; set; }
    public required string Method { get; set; }
    public required string Status { get; set; }
    public string? DetailJson { get; set; }
}

// Mapping tables below mirror the committed seed files under data/reference/ on every import.
public sealed class UsdaTraitType
{
    public required string TypeUri { get; set; }
    public required string Key { get; set; }
    public required string Label { get; set; }
    public required string ValueKind { get; set; }
    public string? Notes { get; set; }
}

public sealed class UsdaCodeLabel
{
    public long Id { get; set; }
    public required string Code { get; set; }
    // Set only when the code means something different for one trait; such a row overrides the generic one.
    public string? TypeUri { get; set; }
    public string? Label { get; set; }
    public int? Ordinal { get; set; }
    public required string Confidence { get; set; }
    public string? Evidence { get; set; }
}

public sealed class PlaceLabel
{
    public required string Scheme { get; set; }
    public required string PlaceId { get; set; }
    public required string Name { get; set; }
    public required string Kind { get; set; }
    public string? CountryCode { get; set; }
    public string? AdminCode { get; set; }
}
