namespace AnythingCanBeFarming.Data;

// Reference data only. Wikipedia text is CC BY-SA 4.0: store it unmodified, show it with its attribution
// (Url, LastRevId, License, LicenseUrl) wherever it appears, and never render it as HTML.
public sealed class WikipediaArticle
{
    public long Id { get; set; }
    public required string Wiki { get; set; }
    // The sitelink title exactly as stored on the Wikidata item.
    public required string RequestedTitle { get; set; }
    // The title after normalization and redirects.
    public string? Title { get; set; }
    public long? PageId { get; set; }
    // The revision LeadText was extracted from (for a disambiguation page, the revision that was checked).
    public long? LastRevId { get; set; }
    public string? WikibaseItem { get; set; }
    public string? ShortDescription { get; set; }
    public string? LeadText { get; set; }
    // Generated by PostgreSQL from LeadText; never written by the application.
    public int? LeadChars { get; private set; }
    public required string Status { get; set; }
    public string? Url { get; set; }
    public required string License { get; set; }
    public required string LicenseUrl { get; set; }
    public DateTimeOffset? FetchedAt { get; set; }
    public bool IsCurrent { get; set; }
    public long ImportId { get; set; }
}

// Mirrors the current Wikidata sitelinks: normally one item per article, but modeled explicitly.
public sealed class WikipediaItemArticle
{
    public long ItemId { get; set; }
    public long ArticleId { get; set; }
}

public static class WikipediaArticleStatus
{
    // Selected but not yet checked (for example, beyond a --limit or after an interrupted run).
    public const string Pending = "Pending";
    public const string Ok = "Ok";
    public const string Missing = "Missing";
    public const string Disambiguation = "Disambiguation";
    // The article belongs to a different Wikidata item. Its lead is kept for inspection; the catalog must not use it.
    public const string ItemMismatch = "ItemMismatch";
    public const string EmptyLead = "EmptyLead";
}

public static class WikipediaLicense
{
    public const string Name = "CC BY-SA 4.0";
    public const string Url = "https://creativecommons.org/licenses/by-sa/4.0/";
}
