// <auto-generated />
using System;
using AnythingCanBeFarming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnythingCanBeFarming.Data.Migrations
{
    [DbContext(typeof(AcbfDbContext))]
    [Migration("20260925000338_AddWfoReference")]
    partial class AddWfoReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatasetVersion")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("RowsImported")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsRead")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsRejected")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("WarningCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileHash");

                    b.ToTable("wfo_import", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoTaxon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AcceptedNameUsageId")
                        .HasColumnType("text");

                    b.Property<long?>("AcceptedTaxonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .HasColumnType("text");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("InfraspecificEpithet")
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalId")
                        .HasColumnType("text");

                    b.Property<string>("MajorGroup")
                        .HasColumnType("text");

                    b.Property<string>("NameAccordingToId")
                        .HasColumnType("text");

                    b.Property<string>("NamePublishedIn")
                        .HasColumnType("text");

                    b.Property<string>("NomenclaturalStatus")
                        .HasColumnType("text");

                    b.Property<string>("OriginalNameUsageId")
                        .HasColumnType("text");

                    b.Property<long?>("OriginalTaxonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentNameUsageId")
                        .HasColumnType("text");

                    b.Property<string>("References")
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameAuthorship")
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameId")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("SpecificEpithet")
                        .HasColumnType("text");

                    b.Property<string>("Subfamily")
                        .HasColumnType("text");

                    b.Property<string>("Subgenus")
                        .HasColumnType("text");

                    b.Property<string>("Subtribe")
                        .HasColumnType("text");

                    b.Property<string>("TaxonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxonRank")
                        .HasColumnType("text");

                    b.Property<string>("TaxonRemarks")
                        .HasColumnType("text");

                    b.Property<string>("TaxonomicStatus")
                        .HasColumnType("text");

                    b.Property<string>("TplId")
                        .HasColumnType("text");

                    b.Property<string>("Tribe")
                        .HasColumnType("text");

                    b.Property<string>("VerbatimTaxonRank")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("WfoCreatedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("WfoModifiedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedNameUsageId");

                    b.HasIndex("AcceptedTaxonId");

                    b.HasIndex("Family");

                    b.HasIndex("Genus");

                    b.HasIndex("ImportId");

                    b.HasIndex("IsCurrent");

                    b.HasIndex("OriginalTaxonId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentNameUsageId");

                    b.HasIndex("ScientificName");

                    b.HasIndex("ScientificNameId");

                    b.HasIndex("SpecificEpithet");

                    b.HasIndex("TaxonId")
                        .IsUnique();

                    b.HasIndex("TaxonRank");

                    b.HasIndex("TaxonomicStatus");

                    b.HasIndex("TplId");

                    b.ToTable("wfo_taxon", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoTaxon", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", "AcceptedTaxon")
                        .WithMany()
                        .HasForeignKey("AcceptedTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.WfoImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", "OriginalTaxon")
                        .WithMany()
                        .HasForeignKey("OriginalTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptedTaxon");

                    b.Navigation("OriginalTaxon");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
