// <auto-generated />
using System;
using AnythingCanBeFarming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnythingCanBeFarming.Data.Migrations
{
    [DbContext(typeof(AcbfDbContext))]
    [Migration("20260926230924_AddWikipediaReference")]
    partial class AddWikipediaReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnythingCanBeFarming.Data.PlaceLabel", b =>
                {
                    b.Property<string>("Scheme")
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.Property<string>("AdminCode")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Scheme", "PlaceId");

                    b.HasIndex("CountryCode", "AdminCode");

                    b.ToTable("place_label", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.SourceImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("RowsInserted")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsRead")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsRetired")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsUpdated")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("WarningCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Kind", "Status");

                    b.ToTable("source_import", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaCodeLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<int?>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("TypeUri")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code", "TypeUri")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Code", "TypeUri"), false);

                    b.ToTable("usda_code_label", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaDistribution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.Property<string>("PlaceRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceScheme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RemarkId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsdaTaxonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("RemarkId");

                    b.HasIndex("Symbol");

                    b.HasIndex("Kind", "PlaceId");

                    b.HasIndex("UsdaTaxonId", "Kind", "PlaceRaw")
                        .IsUnique();

                    b.ToTable("usda_distribution", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyPartUri")
                        .HasColumnType("text");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("LifeStageUri")
                        .HasColumnType("text");

                    b.Property<long?>("MethodRemarkId")
                        .HasColumnType("bigint");

                    b.Property<string>("OccurrenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RemarkId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceTerm")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("StatisticalMethod")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitUri")
                        .HasColumnType("text");

                    b.Property<long>("UsdaTaxonId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValueCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("CASE WHEN \"ValueRaw\" ~ '^https?://' THEN regexp_replace(\"ValueRaw\", '^.*[/#]', '') ELSE \"ValueRaw\" END", true);

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("MethodRemarkId");

                    b.HasIndex("RemarkId");

                    b.HasIndex("Symbol");

                    b.HasIndex("TypeUri");

                    b.HasIndex("UsdaTaxonId");

                    b.HasIndex("TypeUri", "ValueRaw");

                    b.ToTable("usda_fact", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaRemark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("usda_remark", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaTaxon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalName")
                        .HasColumnType("text");

                    b.Property<string>("FamilyUsda")
                        .HasColumnType("text");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxonRank")
                        .HasColumnType("text");

                    b.Property<string>("TaxonomicStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("ImportId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("usda_taxon", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaTraitType", b =>
                {
                    b.Property<string>("TypeUri")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TypeUri");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("usda_trait_type", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaWfoLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcceptedWfoTaxonId")
                        .HasColumnType("bigint");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsdaTaxonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WfoTaxonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedWfoTaxonId");

                    b.HasIndex("Symbol");

                    b.HasIndex("UsdaTaxonId")
                        .IsUnique();

                    b.HasIndex("WfoTaxonId");

                    b.ToTable("usda_wfo_link", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoDeduplicatedId", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorsString")
                        .HasColumnType("text");

                    b.Property<string>("CanonicalName")
                        .HasColumnType("text");

                    b.Property<long?>("DeprecatedTaxonId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeprecatedWfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("NomenclaturalStatus")
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .HasColumnType("text");

                    b.Property<long?>("ReplacementTaxonId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReplacementWfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeprecatedTaxonId");

                    b.HasIndex("DeprecatedWfoId")
                        .IsUnique();

                    b.HasIndex("ImportId");

                    b.HasIndex("ReplacementTaxonId");

                    b.HasIndex("ReplacementWfoId");

                    b.ToTable("wfo_deduplicated_id", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoDeprecatedName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorsString")
                        .HasColumnType("text");

                    b.Property<string>("CanonicalName")
                        .HasColumnType("text");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("NomenclaturalStatus")
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .HasColumnType("text");

                    b.Property<string>("WfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("WfoTaxonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("ImportId");

                    b.HasIndex("Rank");

                    b.HasIndex("WfoId")
                        .IsUnique();

                    b.HasIndex("WfoTaxonId");

                    b.ToTable("wfo_deprecated_name", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatasetKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Backbone");

                    b.Property<string>("DatasetVersion")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("RowsImported")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsRead")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsRejected")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("WarningCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileHash");

                    b.ToTable("wfo_import", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoIpniMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("IpniId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedIpniId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("WfoTaxonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("IpniId");

                    b.HasIndex("NormalizedIpniId");

                    b.HasIndex("WfoId");

                    b.HasIndex("WfoTaxonId");

                    b.HasIndex("IpniId", "WfoId")
                        .IsUnique();

                    b.ToTable("wfo_ipni_mapping", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoTaxon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AcceptedNameUsageId")
                        .HasColumnType("text");

                    b.Property<long?>("AcceptedTaxonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .HasColumnType("text");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("InfraspecificEpithet")
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalId")
                        .HasColumnType("text");

                    b.Property<string>("MajorGroup")
                        .HasColumnType("text");

                    b.Property<string>("NameAccordingToId")
                        .HasColumnType("text");

                    b.Property<string>("NamePublishedIn")
                        .HasColumnType("text");

                    b.Property<string>("NomenclaturalStatus")
                        .HasColumnType("text");

                    b.Property<string>("OriginalNameUsageId")
                        .HasColumnType("text");

                    b.Property<long?>("OriginalTaxonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentNameUsageId")
                        .HasColumnType("text");

                    b.Property<string>("References")
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameAuthorship")
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameId")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("SpecificEpithet")
                        .HasColumnType("text");

                    b.Property<string>("Subfamily")
                        .HasColumnType("text");

                    b.Property<string>("Subgenus")
                        .HasColumnType("text");

                    b.Property<string>("Subtribe")
                        .HasColumnType("text");

                    b.Property<string>("TaxonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxonRank")
                        .HasColumnType("text");

                    b.Property<string>("TaxonRemarks")
                        .HasColumnType("text");

                    b.Property<string>("TaxonomicStatus")
                        .HasColumnType("text");

                    b.Property<string>("TplId")
                        .HasColumnType("text");

                    b.Property<string>("Tribe")
                        .HasColumnType("text");

                    b.Property<string>("VerbatimTaxonRank")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("WfoCreatedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("WfoModifiedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedNameUsageId");

                    b.HasIndex("AcceptedTaxonId");

                    b.HasIndex("Family");

                    b.HasIndex("Genus");

                    b.HasIndex("ImportId");

                    b.HasIndex("IsCurrent");

                    b.HasIndex("OriginalTaxonId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentNameUsageId");

                    b.HasIndex("ScientificName");

                    b.HasIndex("ScientificNameId");

                    b.HasIndex("SpecificEpithet");

                    b.HasIndex("TaxonId")
                        .IsUnique();

                    b.HasIndex("TaxonRank");

                    b.HasIndex("TaxonomicStatus");

                    b.HasIndex("TplId");

                    b.HasIndex(new[] { "Genus" }, "IX_wfo_taxon_Genus_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Genus" }, "IX_wfo_taxon_Genus_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Genus" }, "IX_wfo_taxon_Genus_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "ScientificName" }, "IX_wfo_taxon_ScientificName_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "ScientificName" }, "IX_wfo_taxon_ScientificName_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "ScientificName" }, "IX_wfo_taxon_ScientificName_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("wfo_taxon", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataCommonName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompactName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("replace(replace(\"NormalizedName\", ' ', ''), '-', '')", true);

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Language", "Name")
                        .IsUnique();

                    b.HasIndex(new[] { "CompactName" }, "IX_wikidata_common_name_CompactName_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "CompactName" }, "IX_wikidata_common_name_CompactName_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "CompactName" }, "IX_wikidata_common_name_CompactName_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "NormalizedName" }, "IX_wikidata_common_name_NormalizedName_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "NormalizedName" }, "IX_wikidata_common_name_NormalizedName_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "NormalizedName" }, "IX_wikidata_common_name_NormalizedName_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("wikidata_common_name", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataExternalId", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Property", "Value");

                    b.HasIndex("ItemId", "Property", "Value")
                        .IsUnique();

                    b.ToTable("wikidata_external_id", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CrosswalkImportId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DetailsFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DetailsImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("EnwikiTitle")
                        .HasColumnType("text");

                    b.Property<string>("ImageFile")
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("LabelEn")
                        .HasColumnType("text");

                    b.Property<long?>("LastRevId")
                        .HasColumnType("bigint");

                    b.Property<string>("Qid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxonName")
                        .HasColumnType("text");

                    b.Property<string>("TaxonRankQid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CrosswalkImportId");

                    b.HasIndex("DetailsImportId");

                    b.HasIndex("IsCurrent");

                    b.HasIndex("Qid")
                        .IsUnique();

                    b.ToTable("wikidata_item", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataWfoLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcceptedWfoTaxonId")
                        .HasColumnType("bigint");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Qid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolvedWfoId")
                        .HasColumnType("text");

                    b.Property<string>("StatementRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("WfoTaxonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedWfoTaxonId");

                    b.HasIndex("ImportId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WfoId");

                    b.HasIndex("WfoTaxonId");

                    b.HasIndex("Qid", "WfoId")
                        .IsUnique();

                    b.ToTable("wikidata_wfo_link", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikipediaArticle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastRevId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LeadChars")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("char_length(\"LeadText\")", true);

                    b.Property<string>("LeadText")
                        .HasColumnType("text");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PageId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Wiki")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WikibaseItem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("Status");

                    b.HasIndex("WikibaseItem");

                    b.HasIndex("Wiki", "RequestedTitle")
                        .IsUnique();

                    b.ToTable("wikipedia_article", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikipediaItemArticle", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("wikipedia_item_article", "reference");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaDistribution", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.SourceImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.UsdaRemark", null)
                        .WithMany()
                        .HasForeignKey("RemarkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.UsdaTaxon", null)
                        .WithMany()
                        .HasForeignKey("UsdaTaxonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaFact", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.SourceImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.UsdaRemark", null)
                        .WithMany()
                        .HasForeignKey("MethodRemarkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.UsdaRemark", null)
                        .WithMany()
                        .HasForeignKey("RemarkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.UsdaTaxon", null)
                        .WithMany()
                        .HasForeignKey("UsdaTaxonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaTaxon", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.SourceImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.UsdaWfoLink", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("AcceptedWfoTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.UsdaTaxon", null)
                        .WithMany()
                        .HasForeignKey("UsdaTaxonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("WfoTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoDeduplicatedId", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("DeprecatedTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.WfoImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("ReplacementTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoDeprecatedName", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WfoImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("WfoTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoIpniMapping", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WfoImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("WfoTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WfoTaxon", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", "AcceptedTaxon")
                        .WithMany()
                        .HasForeignKey("AcceptedTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.WfoImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", "OriginalTaxon")
                        .WithMany()
                        .HasForeignKey("OriginalTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptedTaxon");

                    b.Navigation("OriginalTaxon");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataCommonName", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WikidataItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataExternalId", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WikidataItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataItem", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.SourceImport", null)
                        .WithMany()
                        .HasForeignKey("CrosswalkImportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.SourceImport", null)
                        .WithMany()
                        .HasForeignKey("DetailsImportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikidataWfoLink", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("AcceptedWfoTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnythingCanBeFarming.Data.SourceImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WikidataItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WfoTaxon", null)
                        .WithMany()
                        .HasForeignKey("WfoTaxonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikipediaArticle", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.SourceImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnythingCanBeFarming.Data.WikipediaItemArticle", b =>
                {
                    b.HasOne("AnythingCanBeFarming.Data.WikipediaArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnythingCanBeFarming.Data.WikidataItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
